### ISSUE TITLE
sssd sudoers do not work on CentOS 5.10 

### ISSUE THREAD

**Issue by jessehu** [tas50/chef-sssd_ldap#13]
When using "sudoers:    files sss" on CentOS 6.5, I can login a user added in OpenLDAP Server and run 'sudo vi', but it doesn't work on  CentOS 5.10 and complaining "<username> is not in the sudoers file"
When using "sudoers:    files ldap" on my CentOS 6.5 or 5.10, the sudo doesn't work.

On CentOS 6.5, the sssd version is sssd-1.11.6-30.el6_6.3.x86_64 (install from official CentOS 6 repo)
On CentOS 5.10, the sssd version is sssd-1.9.5-0.el5 (installed from https://repos.fedorapeople.org/repos/jhrozek/sssd-libs/epel-5/x86_64/)

This is my /etc/nsswitch.conf:

passwd:     files sss
shadow:     files sss
group:      files sss

hosts:      files dns
bootparams: nisplus [NOTFOUND=return] files

ethers:     files
netmasks:   files
networks:   files
protocols:  files
rpc:        files
services:   files

netgroup:   nisplus
publickey:  nisplus

automount:  files nisplus
aliases:    files nisplus

sudoers:    files sss

This is my /etc/sssd/sssd.conf ;
[sssd]
config_file_version = 2
services = nss, pam, sudo
domains = LDAP
......

**Comment by tas50** [comment]
The version of the package in RHEL 5 doesn't support sudo.  I've gated the sudo service to not install on RHEL < 6
